 # Numpy

In [1]:
import numpy as np # Aktifin ini dulu gan

In [2]:
a = np.array([[1,2,3,4], 
             [5,6,7,8], 
             [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
print(a[0])

[1 2 3 4]


In [4]:
a.ndim #Dimensi

2

In [5]:
a.shape #Bentuk

(3, 4)

In [6]:
a = np.array([1,2,3])

In [7]:
a.ndim

1

In [8]:
a.shape

(3,)

In [9]:
np.zeros(6) # (6,)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((6, 2)) #(6,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
form1 = [(4,1)]

In [12]:
ones1 = np.ones((6,2))
print(ones1)

form1 = ((4,5))
ones2 = np.ones(form1)
print(ones2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
ones3 = np.ones((2,3,2))
ones3

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [14]:
numbers = np.full((2,4), 7)
numbers

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [15]:
numbers = np.full((2,4), 7, dtype=np.float16)
numbers

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.]], dtype=float16)

In [16]:
empty_array = np.empty(6)
empty_array

array([0., 0., 0., 0., 0., 0.])

In [17]:
print(np.arange(4))
print(np.arange(0, 10, 2))

[0 1 2 3]
[0 2 4 6 8]


In [18]:
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [19]:
np.arange(2, 21, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
np.arange(1, 21, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [22]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

## Add Remove Sort

In [23]:
arr = np.array([1,2,3,4,5,6,7,8])
np.append(arr, [1,2])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
arr_new = np.append(arr, [1,2])
arr_new.shape

(10,)

In [25]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [26]:
np.delete(arr, 6)

array([1, 2, 3, 4, 5, 6, 8])

In [27]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr2d = np.array([[9,18, 3, 7],
                  [2, 1, 10, 34],
                  [51 18, 10, 43]
                 ])

np.sort(arr2d, axis-0)
np.sort(arr2d, axis=1)

SyntaxError: invalid syntax (4292120498.py, line 4)

In [ ]:
array_example = np.array([
    [0, 1, 2, 3, 4, 5,6, 7].
])

print(array_example)

In [ ]:
array_example.ndim

In [ ]:
array_example.shape
array_example.size

In [ ]:
array_example.dtype

In [ ]:
array_example.itemsize

In [ ]:
array_example.dtype = np.int16
array_example.dtype

In [ ]:
array_example.itemsize

In [ ]:
array_example.nbytes

In [ ]:
ones3 = np.ones((3,4))
ones3

In [ ]:
ones3.shape

In [ ]:
ones3.reshape(6,2)

In [ ]:
a = np.arange(6)
a

In [ ]:
b = a.reshape(6,3)


In [ ]:
bb = b.reshape(3,6)
bb

In [ ]:
c = a.reshape(3, 1, 2)
c

In [ ]:
a = np.arange(18)
print(a)
d = a.reshape(3,3,2)
print(d)

In [ ]:
np.reshape(d, (9,2))

In [ ]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

In [ ]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

In [ ]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

In [ ]:
data = np.arange(1, 4)

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

In [ ]:
a = np.arange(1, 13).reshape(3, 4)
a

In [ ]:
print(a[a >= 5])

In [ ]:
five_up = (a >= 5)
print(a[five_up])


In [ ]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

In [ ]:
divisible_by_3 = a[a%3==0]
print(divisible_by_3)

In [ ]:
a

In [ ]:
c = a[(a > 2) & (a < 11)]
print(c)

In [ ]:
random_af = np.random.rand(3,5)
print(random_af)
print(random_af.dtype)

In [ ]:
random_ai = np.random.randint(2, high=10, size=5)
print(random_ai)

In [ ]:
arr = np.arange(1, 11)
arr

In [ ]:
arr1 = arr[3:8]
arr1

In [ ]:
a_1 = np.array([[1,1], [2,2]])
a_2 = np.array([[3,3], [4,4]])

In [ ]:
np.vstack((a_1, a_2))

In [ ]:
np.vstack((a_1, a_2, a_1))

In [ ]:
np.vstack((a_1, a_2, a_1, a_1))

In [ ]:
a_3 = np.array([[3,3,3], [4,4,4]])
np.vstack((a_2, a_3))

In [ ]:
np.hstack((a_1, a_2))

In [ ]:
np.hstack((a_1, a_2, a_1, a_3))

In [ ]:
arrsplit = np.arange(1, 25).reshape(2,12)
print(arrsplit)

In [ ]:
np.hsplit(arrsplit, 3)

In [ ]:
result = np.hsplit(arrsplit, 3)
result[0]

In [ ]:
result[1]

In [ ]:
result[2]

In [ ]:
a = np.arange(1,13).reshape(3,4)
a

In [ ]:
b = a.view()
b

In [ ]:
b[1,1] = 10
b

In [ ]:
a

In [ ]:
a = np.arange(1,13).reshape(3,4)
a

In [ ]:
c = a.copy()
c

In [ ]:
c[:, -1] = 0
c

In [ ]:
a

In [ ]:
a

In [ ]:
b

In [ ]:
c

In [ ]:
a + c

In [ ]:
a * c

In [ ]:
a / b

In [ ]:
a = np.array([1, 2, 3, 4])

a.sum()

In [ ]:
a.mean()

In [ ]:
b = np.array([[1,1], [2,2]])
b

In [ ]:
b.sum(axis = 0)

In [ ]:
b.sum(axis = 1)

In [ ]:
b.mean(axis = 0)

In [ ]:
data = np.arange(1,3)
data

In [ ]:
data * 1.6

In [ ]:
data.shape

In [ ]:
a3x4 = np.ones((3,4))
a3x4

In [ ]:
a4x6 = np.ones((4,6))
a4x6

In [ ]:
np.dot(a3x4, a4x6)

In [ ]:
data

In [ ]:
A = np.random.randint(1, 10, size=12)
A


In [ ]:
A.sum()

In [ ]:
A.mean()

In [ ]:
data = np.arange(1,5).reshape(2,2)
data

In [ ]:
ones_row = np.ones([1, 2])
ones_row

In [ ]:
data + ones_row

In [ ]:
a_2 = np.arange(7,13).reshape(3,2)
print(a_2)
print(a_2.shape)

In [ ]:
data = np.arange(1,7).reshape(3,2)
data

In [ ]:
data.T

In [ ]:
arrflat = np.arange(1,13).reshape(3,4)
print(arrflat)

In [ ]:
flatten_arrflat = arrflat.flatten()
flatten_arrflat

--- Logging error ---
Traceback (most recent call last):
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\site-packages\ipykernel\kernelbase.py", line 461, in dispatch_queue
    await self.process_one()
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\site-packages\ipykernel\kernelbase.py", line 450, in process_one
    await dispatch(*args)
TypeError: object NoneType can't be used in 'await' expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
OSError: [Errno 22] Invalid argument
Call stack:
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _ru