 # Numpy

In [1]:
import numpy as np # Aktifin ini dulu gan

In [2]:
np.array()

TypeError: array() missing required argument 'object' (pos 1)

--- Logging error ---
Traceback (most recent call last):
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\site-packages\ipykernel\kernelbase.py", line 461, in dispatch_queue
    await self.process_one()
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\site-packages\ipykernel\kernelbase.py", line 450, in process_one
    await dispatch(*args)
TypeError: object NoneType can't be used in 'await' expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
OSError: [Errno 22] Invalid argument
Call stack:
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _ru

In [3]:
a[1,3]

NameError: name 'a' is not defined

--- Logging error ---
Traceback (most recent call last):
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\site-packages\ipykernel\kernelbase.py", line 461, in dispatch_queue
    await self.process_one()
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\site-packages\ipykernel\kernelbase.py", line 450, in process_one
    await dispatch(*args)
TypeError: object NoneType can't be used in 'await' expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
OSError: [Errno 22] Invalid argument
Call stack:
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _ru

In [ ]:
a = np.array([[1,2,3,4], 
             [5,6,7,8], 
             [9,10,11,12]])
a

In [6]:
print(a[0])

[1 2 3 4]


In [9]:
a.ndim #Dimensi

2

In [11]:
a.shape #Bentuk

(3, 4)

In [12]:
a = np.array([1,2,3])

In [13]:
a.ndim

1

In [14]:
a.shape

(3,)

In [15]:
np.zeros(6) # (6,)

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((6, 2)) #(6,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
form1 = [(4,1)]

In [22]:
ones1 = np.ones((6,2))
print(ones1)

form1 = ((4,5))
ones2 = np.ones(form1)
print(ones2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
ones3 = np.ones((2,3,2))
ones3

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [25]:
numbers = np.full((2,4), 7)
numbers

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [27]:
numbers = np.full((2,4), 7, dtype=np.float16)
numbers

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.]], dtype=float16)

In [28]:
empty_array = np.empty(6)
empty_array

array([0., 0., 0., 0., 0., 0.])

In [29]:
print(np.arange(4))
print(np.arange(0, 10, 2))

[0 1 2 3]
[0 2 4 6 8]


In [30]:
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [31]:
np.arange(2, 21, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [34]:
np.arange(1, 21, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [36]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

## Add Remove Sort

In [41]:
arr = np.array([1,2,3,4,5,6,7,8])
np.append(arr, [1,2])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
arr_new = np.append(arr, [1,2])
arr_new.shape

(10,)

In [39]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [43]:
np.delete(arr, 6)

array([1, 2, 3, 4, 5, 6, 8])

In [45]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr2d = np.array([[9,18, 3, 7],
                  [2, 1, 10, 34],
                  [51 18, 10, 43]
                 ])

np.sort(arr2d, axis-0)
np.sort(arr2d, axis=1)

SyntaxError: invalid syntax (1967026165.py, line 4)

--- Logging error ---
Traceback (most recent call last):
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\site-packages\ipykernel\kernelbase.py", line 461, in dispatch_queue
    await self.process_one()
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\site-packages\ipykernel\kernelbase.py", line 450, in process_one
    await dispatch(*args)
TypeError: object NoneType can't be used in 'await' expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
OSError: [Errno 22] Invalid argument
Call stack:
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _ru

In [47]:
array_example = np.array([
    [0, 1, 2, 3, 4, 5,6, 7].
])

print(array_example)

[[0 1 2 3 4 5 6 7]]


In [49]:
array_example.ndim

2

In [53]:
array_example.shape
array_example.size

8

In [54]:
array_example.dtype

dtype('int32')

In [55]:
array_example.itemsize

4

In [60]:
array_example.dtype = np.int16
array_example.dtype

dtype('int16')

In [61]:
array_example.itemsize

2

In [63]:
array_example.nbytes

32

In [65]:
ones3 = np.ones((3,4))
ones3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
ones3.shape

(3, 4)

In [67]:
ones3.reshape(6,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [68]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [76]:
b = a.reshape(6,3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [77]:
bb = b.reshape(3,6)
bb

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [72]:
c = a.reshape(3, 1, 2)
c

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [73]:
a = np.arange(18)
print(a)
d = a.reshape(3,3,2)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [74]:
np.reshape(d, (9,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [78]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 18)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]]


In [79]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 18)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]]


In [80]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(18, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]]


In [83]:
data = np.arange(1, 4)

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [84]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


In [86]:
five_up = (a >= 5)
print(a[five_up])


[ 5  6  7  8  9 10 11 12]


In [88]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [89]:
divisible_by_3 = a[a%3==0]
print(divisible_by_3)

[ 3  6  9 12]


In [90]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [96]:
random_af = np.random.rand(3,5)
print(random_af)
print(random_af.dtype)

[[0.36910441 0.3173643  0.58434024 0.62666999 0.00977295]
 [0.66419663 0.87762976 0.14156091 0.99282954 0.32202479]
 [0.22787745 0.26332167 0.24697895 0.45656766 0.72784928]]
float64


In [102]:
random_ai = np.random.randint(2, high=10, size=5)
print(random_ai)

[9 7 2 3 3]


In [104]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [106]:
a_1 = np.array([[1,1], [2,2]])
a_2 = np.array([[3,3], [4,4]])

In [107]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [108]:
np.vstack((a_1, a_2, a_1))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [1, 1],
       [2, 2]])

In [109]:
np.vstack((a_1, a_2, a_1, a_1))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [1, 1],
       [2, 2],
       [1, 1],
       [2, 2]])

In [111]:
a_3 = np.array([[3,3,3], [4,4,4]])
np.vstack((a_2, a_3))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

--- Logging error ---
Traceback (most recent call last):
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\site-packages\ipykernel\kernelbase.py", line 461, in dispatch_queue
    await self.process_one()
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\site-packages\ipykernel\kernelbase.py", line 450, in process_one
    await dispatch(*args)
TypeError: object NoneType can't be used in 'await' expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
OSError: [Errno 22] Invalid argument
Call stack:
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\users\zhafran\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _ru

In [113]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [114]:
np.hstack((a_1, a_2, a_1, a_3))

array([[1, 1, 3, 3, 1, 1, 3, 3, 3],
       [2, 2, 4, 4, 2, 2, 4, 4, 4]])

In [115]:
arrsplit = np.arange(1, 25).reshape(2,12)
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [116]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [117]:
result = np.hsplit(arrsplit, 3)
result[0]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [118]:
result[1]

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [119]:
result[2]

array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])

In [120]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [121]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [122]:
b[1,1] = 10
b

array([[ 1,  2,  3,  4],
       [ 5, 10,  7,  8],
       [ 9, 10, 11, 12]])

In [125]:
a

array([[ 1,  2,  3,  4],
       [ 5, 10,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [132]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [133]:
c[:, -1] = 0
c

array([[ 1,  2,  3,  0],
       [ 5,  6,  7,  0],
       [ 9, 10, 11,  0]])

In [134]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [137]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [138]:
b

array([[ 1,  2,  3,  4],
       [ 5, 10,  7,  8],
       [ 9, 10, 11, 12]])

In [139]:
c

array([[ 1,  2,  3,  0],
       [ 5,  6,  7,  0],
       [ 9, 10, 11,  0]])

In [140]:
a + c

array([[ 2,  4,  6,  4],
       [10, 12, 14,  8],
       [18, 20, 22, 12]])

In [141]:
a * c

array([[  1,   4,   9,   0],
       [ 25,  36,  49,   0],
       [ 81, 100, 121,   0]])

In [142]:
a / b

array([[1. , 1. , 1. , 1. ],
       [1. , 0.6, 1. , 1. ],
       [1. , 1. , 1. , 1. ]])

In [143]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [144]:
a.mean()

2.5

In [145]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [146]:
b.sum(axis = 0)

array([3, 3])

In [147]:
b.sum(axis = 1)

array([2, 4])

In [148]:
b.mean(axis = 0)

array([1.5, 1.5])

In [149]:
data = np.arange(1,3)
data

array([1, 2])

In [152]:
data * 1.6

array([1.6, 3.2])

In [153]:
data.shape

(2,)

In [156]:
a3x4 = np.ones((3,4))
a3x4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [174]:
a4x6 = np.ones((4,6))
a4x6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [175]:
np.dot(a3x4, a4x6)

array([[4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.]])

In [159]:
data

array([1, 2])

In [164]:
A = np.random.randint(1, 10, size=12)
A


array([5, 1, 4, 9, 1, 2, 3, 8, 3, 2, 7, 2])

In [165]:
A.sum()

47

In [166]:
A.mean()

3.9166666666666665

In [167]:
data = np.arange(1,5).reshape(2,2)
data

array([[1, 2],
       [3, 4]])

In [170]:
ones_row = np.ones([1, 2])
ones_row

array([[1., 1.]])

In [172]:
data + ones_row

array([[2., 3.],
       [4., 5.]])

In [173]:
a_2 = np.arange(7,13).reshape(3,2)
print(a_2)
print(a_2.shape)

[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [178]:
data = np.arange(1,7).reshape(3,2)
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [179]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [180]:
arrflat = np.arange(1,13).reshape(3,4)
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [182]:
flatten_arrflat = arrflat.flatten()
flatten_arrflat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])