# Descriptive Statistics

In [1]:
mean_ = 50
median_ = 56
mode_ = 60
stdev_ = 8.5

#Pearson first Coef of Skewness
coef_ = (mean_-mode_) / stdev_
print(coef_)

#Pearson Second Coef of Skewness
coef_ = 3*(mean_-median_) / stdev_
print(coef_)

-1.1764705882352942
-2.1176470588235294


In [2]:
import math
import statistics
import scipy.stats
import pandas as pd
import numpy as np

In [3]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]
print('x: ',x)
print('x with nan: ', x_with_nan)

x:  [8.0, 1, 2.5, 4, 28.0]
x with nan:  [8.0, 1, 2.5, nan, 4, 28.0]


In [4]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

print(y)
print(y_with_nan)
print(z)
print(z_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


In [5]:
mean_ = sum(x) / len(x)
mean_

8.7

In [6]:
mean_ = statistics.mean(x)
mean_

8.7

In [7]:
mean_ = statistics.mean(x_with_nan)
mean_

nan

In [8]:
sum(x_with_nan)

nan

In [9]:
mean_ = np.mean(y)
mean_

8.7

In [10]:
mean_ = y.mean()
mean_

8.7

In [11]:
mean_ = np.mean(y_with_nan)
mean_

nan

In [12]:
mean_ = y_with_nan.mean()
mean_

nan

In [13]:
mean_ = np.nanmean(y_with_nan)
mean_

8.7

In [14]:
mean_ = z.mean()
mean_

8.7

In [15]:
mean_ = z_with_nan.mean()
mean_

8.7

In [16]:
x = [8, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]

wmean = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
print(wmean)

6.95


In [17]:
y, z, w = np.array(x), pd.Series(x), np.array(w)

wmean = np.average(y, weights=w)
print(wmean)

wmean = np.average(z, weights=w)
print(wmean)

6.95
6.95


In [18]:
(w*y).sum() / w.sum()

6.95

In [19]:
hmean = len(x) / sum(1 / item for item in x)
hmean

2.7613412228796843

In [20]:
hmean = statistics.harmonic_mean(x)
hmean

2.7613412228796843

In [21]:
hmean = scipy.stats.hmean(x)
hmean

2.7613412228796843

In [22]:
hmean = scipy.stats.hmean(y)
hmean

2.7613412228796843

In [23]:
hmean = scipy.stats.hmean(z)
hmean

2.7613412228796843

In [24]:
gmean = 1
for item in x:
    gmean *= item

gmean **= 1 / len(x)
gmean

4.677885674856041

In [25]:
gmean = scipy.stats.gmean(y)
gmean

4.67788567485604

In [26]:
gmean = scipy.stats.gmean(z)
gmean

4.67788567485604

In [27]:
n = len(x)
if n%2:
    median_ = sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(x), round(0.5*n)
    median_ = 0.5*(x_ord[index-1] + x_ord[index])

median_

4

In [28]:
median_low= statistics.median_low(x[:-1])
print(median_low)

median_high= statistics.median_high(x[:-1])
print(median_high)

2.5
4


In [29]:
median_low = statistics.median_low(x)
median_low

4

In [30]:
median_ = statistics.median(x)
median_

4

In [31]:
x_with_nan

[8.0, 1, 2.5, nan, 4, 28.0]

In [32]:
print(statistics.median(x_with_nan))
print(statistics.median_low(x_with_nan))
print(statistics.median_high(x_with_nan))

6.0
4
8.0


In [33]:
median_ = np.median(y)
median_

4.0

In [34]:
median_ = np.median(y[:-1])
median_

3.25

In [35]:
u = [2,3,2,8,12]
v = [12,15,12,15,21,15,12]

mode_ = max((u.count(item), item) for item in set (u))[1]
mode_

2

In [36]:
mode_ = statistics.mode(u)
mode_

2

In [37]:
u,v = np.array(u), np.array(v)

mode_ = scipy.stats.mode(u)
mode_

ModeResult(mode=array([2]), count=array([2]))

In [38]:
vv = [12,15,12,15,21,15,12,12,12,15,15,15]

u,vv = np.array(u), np.array(vv)

mode_ = scipy.stats.mode(vv)
mode_

ModeResult(mode=array([15]), count=array([6]))

In [39]:
print(mode_.mode)
print(mode_.count)

[15]
[6]


In [40]:
v

array([12, 15, 12, 15, 21, 15, 12])

In [41]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2,2,math.nan])

print(u.mode())
print(v.mode())
print(w.mode())

0    2
dtype: int32
0    12
1    15
dtype: int32
0    2.0
dtype: float64


In [42]:
v

0    12
1    15
2    12
3    15
4    21
5    15
6    12
dtype: int32

In [43]:
n = len(x)

mean_ = sum(x)/n

var_ = sum((item - mean_)**2 for item in x) / (n-1)
var_

123.19999999999999

In [44]:
var_ = statistics.variance(x)
var_

123.2

In [45]:
var_ = np.var(y, ddof=1)
var_

123.19999999999999

In [46]:
var_ = y.var(ddof=1)
var_

123.19999999999999

In [47]:
var_ = z.var(ddof=1)
var_

123.19999999999999

In [48]:
std_ = var_**0.5
std_

11.099549540409285

In [49]:
std_ = statistics.stdev(x)
std_

11.099549540409287

In [50]:
std_ = np.std(y, ddof=1)
std_

11.099549540409285

In [51]:
std_ = y.std(ddof=1)
std_

11.099549540409285

In [52]:
x = [8, 1, 2.5, 4, 28.0]

n = len(x)

mean_ = sum(x)/n

var_ = sum((item - mean_)**2 for item in x) / (n-1)
std_ = var_ ** 0.5


In [53]:
y, y_with_nan = np.array(x), np.array(x_with_nan)

skew_ = scipy.stats.skew(y, bias=False)
skew_

1.9470432273905927

In [54]:
skew_ = scipy.stats.skew(y_with_nan, bias=False, nan_policy='omit'),
skew_

(masked_array(data=1.94704323,
              mask=False,
        fill_value=1e+20),)

In [55]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

z.skew()

1.9470432273905924

In [56]:
skew_ = scipy.stats.skew(y_with_nan, bias=False, nan_policy='propagate'),
skew_

(nan,)

In [57]:
x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.0, 21.0, 25.8, 41.0]
statistics.quantiles(x, n=2)

[8.0]

In [58]:
x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.0, 21.0, 25.8, 41.0]
statistics.quantiles(x, n=4, method='inclusive')

[0.1, 8.0, 21.0]

In [59]:
y = np.array(x)
np.percentile(y, 5)

-3.44

In [60]:
np.percentile(y, 95)

34.919999999999995

In [61]:
np.percentile(y, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [62]:
np.median(y)

8.0

In [63]:
np.percentile(y_with_nan, [25, 50, 75])

array([nan, nan, nan])

In [64]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([2.5, 4. , 8. ])

In [65]:
np.ptp(y)

46.0